name = "hello-world-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-01-01"
account_id = "8f58b8f2bca2bbc0e8bd901bae9299a5"

# Build configuration
[build]
command = "npm run build"

# Environment variables (use wrangler secret for sensitive data)
# [vars]
# EXAMPLE_VAR = "value"

# Secrets (set via: wrangler secret put SECRET_NAME)
# - OPENAI_API_KEY
# - DATABASE_URL
# etc.
