name = "{{PROJECT_NAME}}-mcp-server"
main = "src/index.ts"
compatibility_date = "2024-10-01"
compatibility_flags = ["nodejs_compat"]

# Build configuration
[build]
command = "npm run build"

# Environment variables (use wrangler secret for sensitive data)
# [vars]
# EXAMPLE_VAR = "value"

# Secrets (set via: wrangler secret put SECRET_NAME)
# - OPENAI_API_KEY
# - DATABASE_URL
# etc.
